# These options require nightly rustfmt
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"

# Stable rustfmt options
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4