[build]
# Default build target for ESP32-S3 (Xtensa)
target = "xtensa-esp32s3-none-elf"

[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[target.'cfg(target_arch = "xtensa")']
runner    = "espflash flash --monitor --log-format defmt"
rustflags = [
  # Link script + defmt script
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "info"

[unstable]
build-std = ["core"]
